# Hack the server
# A group of pre made servers that you can break
# Github://www.github.com/lewisevans2007/hack_the_server
# By: Lewis Evans

PYTHON=python3
SRC = src/main.py

all: run

run:
	$(PYTHON) $(SRC)